version: '3.9'

services:
  api:
    container_name: frogpay-api
    image: frogpay-api-image
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4652:8080
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Database=TesteFrogPay;Username=postgres;Password=mysecretpassword;"
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - db

  db:
    container_name: frogpay-db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: TesteFrogPay
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}